### ISSUE TITLE
Inaccuracies with utapi metrics outputted to Redis bound on localhost

### ISSUE THREAD

**Issue by mutex007** [scality/S3#1058]
I have been running a setup with a companion Redis instance to output the utapi metrics but found out after two months the metrics are inaccurate for some buckets. The Redis is running on localhost and connected to the S3 api server but i have seen inaccurate bucket counts. The only metric which is accurate after two months is the "s3:buckets:$:storageUtilized:counter".

The following below metrics have inaccuracies:
s3:accounts:" + canonical_id + ":numberOfObjects:counter  -- Highly inaccurate
s3:accounts:" + canonical_id + ":storageUtilized:counter  -- Highly inaccurate
s3:buckets:" + BucketName  + ":numberOfObjects:counter -- Accurate most of the time, only inaccurate 
for one bucket.

We are able to test the accuracy mainly because we run only the S3 api on top of our own internal backend which we can run queries against.

Can you advice if you have seen similar issues in your environment.

Thanks

**Comment by rahulreddy** [comment]
Hi,

Sorry to reply late.

It's possible that the metrics could go out of date if Redis missed some events because it was intermittently down.
You can manually set the global counters that you listed to correct the values.
To avoid this in our production usage we have a local cache (basically a non-persistent Redis) and a Redis Sentinel cluster(for persistence) and we the Utapi Replay feature which caches the metrics locally if the Sentinel is down for some reason and replays the metrics back when it's online.  UtapiReplay should be running the background for this feature to work and can be started using
`npm run utapi_replay` command.
