### ISSUE TITLE
using db for authentication

### ISSUE THREAD

**Issue by siamackSeifi** [scality/S3#1257]
Hi.

Is it possible to config server to use db instead of json file or params for authdata,
or it has not been implemented yet?
or there is no plan about it :)
i couldn't find anything.

tnx

**Comment by smaffulli** [comment]
Hi @siamackSeifi for open-ended questions like this one it's better to use [Zenko forums](https://forum.zenko.io) instead of Issues. I'm quite curious about your use cases too: it's very helpful for the whole team to understand how Cloudserver and Zenko are being used so we can better prioritize new features and bug fixes. Would you mind describing how you you're using Cloudserver on https://forum.zenko.io/t/how-do-you-use-zenko-and-its-components/246?

**Comment by rahulreddy** [comment]
Closing as the issue has been moved to Zenko forums.
