### ISSUE TITLE
add ability to customize accessKey/secretKey

### ISSUE THREAD

**Issue by poblin-orange** [scality/S3#213]
Nice tool for S3 integration tests !
It would be very usefull to be able to set custom accesKey secretKey as env variable.

**Comment by DavidPineauScality** [comment]
Hello @poblin-orange,

Do you know if you're using the File/memory backends ? This would mean using the S3server container or S3 by itself, running it with a `npm start `.

If yes, then it is fairly easy, and you only need to edit one file: https://github.com/scality/S3/blob/master/conf/authdata.json . If you are using the container, you can provide this file and override the default one through a docker file mapping with the option `-v $ABSOLUTE_HOST_PATH:/home/scality/S3/conf/authdata.json`. Otherwise, simply editing the file should be enough.

Would that be enough for your needs ?

**Comment by poblin-orange** [comment]
Hello @DavidPineauScality 
im just using the docker image out of the box. Suspect the data is stored in the container, and ill docker mount a volume.
Thanks for the tip to change the credentials. 2 Env vars would be convenient though :-)

**Comment by DavidPineauScality** [comment]
Well, env vars would be limited, as we cannot provide an infinity of tunables through env vars while staying consistent. Since the file format allows to add new accounts/users/accessKeys, we thought that it would be more than enough for this type of need.
Hopefully this will work and address your current need ! Please keep us updated on this, and close the issue if your problem is addressed.

**Comment by aperigault** [comment]
Hello,

We are thinking to use Scality S3 server in production (approximately 1To of data) but the last problem is the users management. If I understand to create new users and roles I need to change authdata.json and restart docker container ?
Currently there is no other solution to manage users and roles (via S3 IAM API for example) ? Stopping service to add users can be a problem.

Tell me if this is not the right place to talk about it.

Thanks

**Comment by DavidPineauScality** [comment]
Hello @aperigault,

Indeed, the current limitation is that the server needs to be restarted if you want to change the users at run-time. Given your needs, maybe having S3Server support signals such as SIGUSR1 to force a reload of the configuration in a smooth way (probably the simplest solution to answer your need) may be enough ?

I cannot promise anything, although if this idea sounds OK for you, contributions are welcome, and/or I could check internally if it is possible to allocate some resources for this.

**Comment by aperigault** [comment]
@DavidPineauScality,

Add a reload feature could be a good think but credentials remain unencrypted in config file. I don't understand exactly ``lib/auth/vault.js`` goal (I'm not a dev) but it could be a good think to use others authentication backends like **hashicorp vault** to store sensitive informations.

**Comment by DavidPineauScality** [comment]
Although the names are far from perfect ("vault" instead of "auth" both in the filename and env variables), the aim of vault.js was to be a wrapper for various authentication backends. As such, it would be possible to provide a new backend for whatever inspires your trust.

As for Scality's Vault, it is a private project, completely different from hashicorp vault, that comes with Scality's RING and S3 connector (a real and efficient distributed large-scale storage backend using the S3 code as front-end).

**Comment by aperigault** [comment]
After talk with my coworkers we will use authdata.json but I will try to encrypt secret keys. Do you think this feature could be merge in master ?
I will be happy if you have internal resource for reload feature.

**Comment by GiorgioRegni** [comment]
You're correct @aperigault, it's not possible to sault the secret key. Would it make sense to encrypt the authdata.json file instead?

**Comment by aperigault** [comment]
@GiorgioRegni: If the key used to encrypt the authdata.json is store in setting file next to auth.json I don't think it's necessary.

**Comment by nicolas2bert** [comment]
Using S3 server with Docker, it is now possible to pass an access key and secret key as environment variables.

https://github.com/scality/S3/blob/master/DOCKER.md#access_key-and-secret_key
