### ISSUE TITLE
Config Questions

### ISSUE THREAD

**Issue by HmarksDeepStorage** [scality/S3#350]
First let me be clear and say I'm a storage guy from the MS-DOS, Windows world. As such much of the documentation for s3server makes knowledge assumptions that the reader knows more than a trivial amount about Node.js or even Docker.

I have s3Server setup on a virtual Centos 7 machine and have the basics running BUT have questions:

1. Are there capacity or other limitations
2. What are the file system storage options?
-  Local FS
- Folder in local FS
- NFS mount
3. How do I specify the storage location for each of the above options?
4. How do I change the access key and secret?
5. Should HTTPS work on the same port 8000 if I use the –p 8000:8000 startup option?  Cyberduck likes to complain about open links

Thanks

**Comment by nicolas2bert** [comment]
Hello @HmarksDeepStorage, we are currently looking at your ticket. We will get back to you soon.

**Comment by nicolas2bert** [comment]
Hey @HmarksDeepStorage

Let's go step by step through:

**1-** 
There are no S3server limitations.

**2-3-** 
S3Server runs with a file backend by default.
So, by default, the data are stored inside your S3server Docker container.
However, you can use Docker volumes to host the data and the metadata of the S3server container outside your S3server Docker container, .
```docker run -­v $(pwd)/data:/usr/src/app/localData -­v $(pwd)/metadata:/usr/src/app/localMetadata -p 8000:8000 ­-d scality/s3server```

In regard to the NFS mount, Docker has several volume plugins that you can use depending on your use-cases.
https://docs.docker.com/engine/extend/legacy_plugins/#/volume-plugins

**4-** 
You need to edit this file: https://github.com/scality/S3/blob/master/conf/authdata.json
If you are using the Docker container, you can provide this file and override the default one using Docker volume. 
```docker run ­-v $(pwd)/authdata.json:/usr/src/app/conf/authdata.json ­­-p 8000:8000 ­-d scality/s3server```
where ./data and ./metadata are in your current directory, but it can also be any mount point, like /mnt/data /mnt/metadata.
Otherwise, simply editing the file should be enough.

**5-** 
Yes, HTTPS works on the same port 8000 if you use the –p 8000:8000
You will have to add certFilePaths section to your `config.json` to make HTTPS work:
```
certFilePaths: {
  "key": "YOUR/PRIVATE/KEY/PATH",
  "cert": "YOUR/PUBLIC/KEY/PATH", 
  "ca": "YOUR/CERTIFICATE/AUTHORITY/PATH"  (optional)
}
```

Please, let us know if you have any further questions.

**Comment by nicolas2bert** [comment]
Hey @HmarksDeepStorage, I hope this response has been helpful to you.

Let me know.

**Comment by HmarksDeepStorage** [comment]
Yes that helps a lot.
