### ISSUE TITLE
MultiObjectDelete API refactor -- extract auth params once

### ISSUE THREAD

**Issue by LaurenSpiegel** [scality/S3#371]
Once the arsenal extractParams function is separated from doAuth, only extract params once in a multiObjectDelete call.     

Related to https://github.com/scality/Arsenal/issues/102

**Comment by DavidPineauScality** [comment]
The extractParams function is already separated from doAuth. In my "refactor effort", I've only left doAuth as-is because I kept playing catch-up with the changes made for Vault and S3 features; and chose this way to reduce the quantity of diff I had to re-apply every time.

All the logic present in doAuth should be logic owned by the "user" of Arsenal, the point being:
 * "Client side of auth" uses `extractParams`
 * "Client" sends params to "Server"
 * "Server side of auth" uses `checkSignature` (and can guess V2 or V4 from the params)

Currently, the only logic provided by Arsenal in this case is setting a few params in the RequestContexts, and that should be managed by S3 in the model I envisionned. Of course, Arsenal's `doAuth` is currently calling its internal `vault.checkSignatureV?` but the vault.js logic should disappear from Arsenal, as it's a specific of S3.

Essentially, what you describe is what I called the "Step2" of the auth refactor, that I never had time to get to. but it should be fairly straight-forward now that the first step is done.
