### ISSUE TITLE
Automatically configure hostname for region

### ISSUE THREAD

**Issue by cyril-dussert** [scality/S3#406]
Hi,

I'm trying to deploy S3 on OpenShift, using these images : https://github.com/ryanj/origin-s2i-nodejs for nodeJS 6.

Almost everything is working fine, so I'm trying now to make easier the build and deployment process for S3.
What I wanna do is to automatically set up my application hostname on config.json when the Application route is created, by using ENV variables if possible.

How can I have access to env variables inside the config.json file ? Do you have a better idea ?

Thanks and regards,
Cyril D

**Comment by nicolas2bert** [comment]
For now, you can not use environment variable in order to change your application hostname on config.json.
What you can do is:
- running your s3server Docker container with your own config.json 
`docker run -v $(pwd)/config.json:/usr/src/app/config.json -p 8000:8000 -d scality/s3server`
- modifying the open-source s3server app, changing `config.regions` to `process.env.S3REGIONS` https://github.com/scality/S3/blob/master/lib/Config.js#L45
I made a branch that you can use: https://github.com/scality/S3/tree/BF/hostname-env

**Comment by cyril-dussert** [comment]
I will have a look at it, thank your for your answer
