### ISSUE TITLE
Logging deletes

### ISSUE THREAD

**Issue by LaurenSpiegel** [scality/S3#451]
We are calling batch delete from a number of api's (complete mpu for example).  Instead of logging in services.deleteObject the keys, we should do it in the wrapper to make sure we are not missing any.

**Comment by electrachong** [comment]
We do already log the keys before sending the delete to datastore in the data wrapper, although at the debug level instead of the trace level. We can change that if that addresses your concerns.

My question is, does it make more sense to log the keys immediately after metadata returns success for deleting the object MD? Are there any noteworthy potential points of failure between deleting the MD and logging the object keys in the wrapper delete function, where MD will have been deleted before we logged the keys?

**Comment by LaurenSpiegel** [comment]
Thanks.  I'd rather we were logging in the batch delete wrapper instead of the services function.  That way we will pick up all batch delete calls.  Since we are calling delete with async limit, if it doesn't finish we won't end up calling the logs in the regular delete wrapper.
