### ISSUE TITLE
Compat: Hadoop s3a filesystem compatibility

### ISSUE THREAD

**Issue by stergiotis** [scality/S3#638]
Scality S3 is not compatible with Hadoop's s3a file system client. Writing files from Spark 2.1 (hadoop-aws 2.7.3, aws-java-sdk 1.10.26):
`scala> sc.hadoopConfiguration.set("fs.s3a.impl","org.apache.hadoop.fs.s3a.S3AFileSystem")`
`scala> sc.hadoopConfiguration.set("fs.s3a.access.key","accessKey1")`
`scala> sc.hadoopConfiguration.set("fs.s3a.secret.key","verySecretKey1")`
`scala> sc.hadoopConfiguration.set("fs.s3a.endpoint","mydomain.com")`
`scala> sc.hadoopConfiguration.set("fs.s3a.connection.ssl.enabled","false")`
`scala> sc.parallelize(Array(1)).saveAsTextFile("s3a://mybucket/test.txt")`
fails with
`com.amazonaws.services.s3.model.AmazonS3Exception: Status Code: 405, AWS Service: Amazon S3, AWS Request ID: null, ASW Error Code: null, AWS Error Message: null`
Website Configuration is enabled for this bucket.

**Comment by LaurenSpiegel** [comment]
@stergiotis, I will try writing to Scality S3 with s3a (I have had no problem reading from Scality S3 with s3a).  Question though: are you trying to write to a website endpoint? You can't put to a website endpoint. You can only do head and get requests to a website endpoint. See http://docs.aws.amazon.com/AmazonS3/latest/dev/WebsiteEndpoints.html

**Comment by stergiotis** [comment]
@LaurenSpiegel If the bucket is not configured as website endpoint the write attempt stops very early: "bucket mybucket does not exist". By enabling the website configuration it proceeds a bit further (resulting in the 405 described above). By modifying the conditional on line 111 of lib/routes.js in such a way that e.g. PUT and DELETE will be handled by checkUnsuportedRoutes(...) instead of routeWebsite(...) the actual writing succeeds but the verification steps fail and Spark/Hadoop's s3a will try to DELETE all created keys.

**Comment by LaurenSpiegel** [comment]
@stergiotis, can you try putting the data to a non-website endpoint?  So, your s3a.endpoint would be something like http://127.0.0.1:8000.  I think you are getting odd behavior because the puts and gets are being treated like website requests.

I just played with putting data from hive using hadoop version 2.7.2 and s3a to Scality S3 and it worked fine (not that this is necessarily the same as your setup but indicates it works).

**Comment by stergiotis** [comment]
@LaurenSpiegel Thanks for trying to reproduce the issue. I wasn't aware of the fact that the two endpoint schemes `bucket.domain.tld` and `domain.tld/bucket` do have a different semantic. Do I understand your suggestion correctly that the former does relate to a website endpoint while the later relates to a REST endpoint?

**Comment by LaurenSpiegel** [comment]
`bucket.domain.tld` and `domain.tld/bucket` should behave the same but if you have the domain in the list of `websiteEndpoints` in your `config.json` in Scality S3, all requests hitting that endpoint will be treated differently from a normal request. I suspect that you are hitting a domain recognized by Scality S3 as a website endpoint due to the config so is responding MethodNotAllowed on a PUT (without your code modification).  If you sent the PUT to an endpoint not in the `websiteEndpoints` list it should not give that error.

**Comment by stergiotis** [comment]
@LaurenSpiegel  Okay, got that, sounds plausible. I am glad it may just be a misconfiguration, will have to check that on Monday and will report back. Thank you for the quick response!

**Comment by stergiotis** [comment]
@LaurenSpiegel By bad, after removing the bucket DNS name from `websiteEndpoints` read and write-access from s3a works as expected. Thank you very much for you quick help.
