### ISSUE TITLE
Data corruption after power loss

### ISSUE THREAD

**Issue by Tiduster** [scality/S3#662]
Hi !

This is the next step of #311.

Here is my configuration:
Docker version : 17.03.0-ce
Scality S3 Server version : commit 84a7e6f (I also test with latest docker hub image)
OS : Debian 8.7
Virtualisation system : VMWare 6.0u2
WriteCache is disabled, as I am on a virtual machine

I use 4 volumes:
```
          -v /data/localMetadata:/usr/src/app/localMetadata
          -v /data/localData:/usr/src/app/localData
          -v /data/settings/config.json:/usr/src/app/config.json
          -v /data/settings/authdata.json:/usr/src/app/conf/authdata.json
```

I was testing data integrity and I find something odd.
I use a python script to massively insert jpg file in S3 Server.

If during the test, I power off the virtual machine using VCenter (dirty electrical shutdown), some of the files that were written in the last 30 seconds before shutdown are corrupt. More precisely, they are incomplete.

I did a lot of tries, here are my observations:

1) Here is a sample of the last keys that were written before shutdown:
```
Key:1490267308.4234602 - READ ERROR : ('Connection broken: IncompleteRead(147456 bytes read, 15129 more expected)', IncompleteRead(147456 bytes read, 15129 more expected))
Key:1490267309.099464 - Value:NOT UTF-8
Key:1490267309.2076397 - READ ERROR : ('Connection broken: IncompleteRead(147456 bytes read, 2683 more expected)', IncompleteRead(147456 bytes read, 2683 more expected))
Key:1490267309.547425 - Value:NOT UTF-8
Key:1490267310.1784554 - READ ERROR : ('Connection broken: IncompleteRead(208896 bytes read, 26207 more expected)', IncompleteRead(208896 bytes read, 26207 more expected))
Key:1490267310.6997852 - READ ERROR : ('Connection broken: IncompleteRead(147456 bytes read, 22547 more expected)', IncompleteRead(147456 bytes read, 22547 more expected))
Key:1490267310.920769 - Value:NOT UTF-8
Key:1490267312.0441651 - Value:NOT UTF-8
Key:1490267312.729269 - Value:NOT UTF-8
```
Boto3 detect issue is some of them, but not all, and not the last one.
If you locate the file on disk, you see a valid picture, but the bottom is missing, and the size/md5 don't match original file.

2) Electrical shutdown is the only way I found to experience this kind of corruption.
During the test, I tried to :
- Stop the docker
- Stop the docker daemon
- kill -9 node application
- kill -9 docker process
without experiencing any corruption (that's a very good point).

4) I spoke with my storage engineers. They didn't think this issue could be related to VMWare or our arrays, but to exclude VMWare definitively, I tried on my laptop (with writecache disabled). I mount the docker the same way, use the same script, and observe the same issue.

5) If I wait 30 seconds after the last write before shutting down the virtual machine, there is no corruption.

6) Metadata are always correct and readable (that's another very good point)

After some reading, I found that you can reduce this gap by reducing the **dirty_expire_centisecs** value in sysctl. So, localData writing are async, and the Kernel flush them to disk every 30 seconds by default.

I spoke with my devs, and they say it's not necessarily an issue, just a design choice, and that I should buy an UPS :-) .
As my data is very important, and I don't care about performance, I would prefer not to lose anything, maybe with a new setting in the configuration ?
If there is nothing to correct, maybe the documentation should mention it (and the **dirty_expire_centisecs** solution) because this work very well for me (less than 2 seconds of data loss when properly tweaked).

Best regards,

**Comment by RemiCardona** [comment]
Just a quick thought here (FTR I'm a complete node n00b)

https://github.com/scality/S3/blob/master/lib/data/file/backend.js#L60-L61

Maybe those 2 steps should be reversed? If there's some caching/buffering done by the WriteStream, _maybe_ the `fsync()` should be done _after_ the `fileStream.end()` to make sure the last few bytes are indeed fsync'ed.

This is 100% untested at this point, I'll try to see with @Tiduster if we can test this hypothesis.

Cheers.

**Comment by jonathan-gramain** [comment]
Hi Remi,

I think the issue is exactly that, the write stream has probably cached the last bits of data until end() is called (I think up to 64KB since that seems to be stream's buffer size by default), so fsync() would necessarily not have applied to this last bit, being called earlier.

Thanks for spotting this, we'll fix on our side (actually I'm rewoking this backend so this part of the code will move soon to scality/Arsenal), please confirm if that fixes the corruption issue.

**Comment by jonathan-gramain** [comment]
I wrote a quick and dirty node program and strace it to check what is the order in which syscalls are done.

From what I can see, at the time fsync is called, the fd may or may not have been closed yet by the stream implementation. So I suspect the real issue is around this: making sure we keep the fd open until we issue fsync.

If that is the situation you run into and which causes failure to fsync and possibly incomplete data written after a power failure, you should see the error log "fsync error" with EBADF errno status (unless the fd is reused in the meantime but that's unlikely).

I will try disabling autoClose from the write stream and call fs.close() after the fsync call.

**Comment by jonathan-gramain** [comment]
Well, I didn't pass the `{ end: false }` option to `stream.pipe()` which causes the write stream to stay open until we call `end()` on it, so that explains the fsync errors I saw.

**Comment by jonathan-gramain** [comment]
I think it gets clearer to me now.

The root issue I see is indeed the fact that the write stream gets closed later than the fsync is issued. This may flush outstanding stream buffers and trigger a call to write() or writev(), even if we don't pass actual data to the end() call (this can be easily reproduced by writing small buffers at a time with a dummy read stream piped, 100 bytes each works for me).

However, to properly fix it, moving the call to end() before the call to fsync() is not enough, because all of this is asynchronous, so either the call to fsync may actually happen after everything is flushed and the fd is closed (leading to EBADF), or it may be called before the outstanding writes are done, leading to non-synced data.

So to properly fix, we basically have to:

 - attach the fsync() call to the 'finish' event of the *write* stream, not the 'end' event of the read stream
 - use the `{ autoClose: false }` option when creating the write stream, and call `fs.close()` only after fsync is called, otherwise close() may be called before the 'finish' event listener is called.

**Comment by RemiCardona** [comment]
That looks much better indeed, thanks a lot !

Looking at f341c98, I got worried for a second because the `.end()` got dropped. But I see that `.pipe()` handles that automatically by default.

We'll report back when we get around to testing this. Thanks again for tackling this so quickly.
